export const SET_GAME_STATE = 'SET_GAME_STATE';

export const SET_MATCHES_AMOUNT = 'SET_MATCHES_AMOUNT';

export const SET_CURRENT_MATCHES = 'SET_CURRENT_MATCHES';

export const SET_RESOLVED_MATCHES = 'SET_RESOLVED_MATCHES';

export const SET_PASSED_TIME = 'SET_PASSED_TIME';

export const SET_CURRENT_COUNTDOWN = 'SET_CURRENT_COUNTDOWN';

export const RESET_TIMER = 'RESET_TIMER';

export const SET_IS_TIMER_ACTIVE = 'SET_IS_TIMER_ACTIVE';

export const SET_GAME_MODE = 'SET_GAME_MODE';

export const RESET_GAME_CONTEXT = 'RESET_GAME_CONTEXT';

export const SET_CURRENT_LEVEL = 'SET_CURRENT_LEVEL';

export const SET_CURRENT_SCORE = 'SET_CURRENT_SCORE';
