export const SET_PASSED_TIME = 'SET_PASSED_TIME';

export const SET_CURRENT_COUNTDOWN = 'SET_CURRENT_COUNTDOWN';

export const SET_IS_TIMER_ACTIVE = 'SET_IS_TIMER_ACTIVE';

export const RESET_TIMER = 'RESET_TIMER';
