export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';

export const RESOLVE_MATCHES = 'RESOLVE_MATCHES';

export const SET_RESOLVED_MATCHES = 'SET_RESOLVED_MATCHES';

export const INITIALIZE_MATCHES = 'INITIALIZE_MATCHES';

export const SET_GAME_MODE = 'SET_GAME_MODE';

export const SET_CURRENT_LEVEL = 'SET_CURRENT_LEVEL';

export const SET_LEVELS = 'SET_LEVELS';

export const ADD_TO_SCORE = 'ADD_TO_SCORE';

export const SET_CARD_THEME = 'SET_CARD_THEME';

export const SUBTRACT_FROM_SCORE = 'SUBTRACT_FROM_SCORE';

export const SET_CURRENT_SCORE = 'SET_CURRENT_SCORE';

export const RESET_GAME = 'RESET_GAME';
